project_id = "hcqygoupvgcsdxtzyest"

[functions.generate-government-image]
verify_jwt = false

[functions.whatsapp-otp-send]
verify_jwt = false

[functions.whatsapp-otp-verify-and-login]
verify_jwt = false
