// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcqygoupvgcsdxtzyest.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjcXlnb3Vwdmdjc2R4dHp5ZXN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MzM0OTcsImV4cCI6MjA3MDUwOTQ5N30.ekj1hCjhQfaqvcN1wcUYaUtmSx5f-d4xCtnWpMe3mmc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});