// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Fallback to Cloud values if Vite env vars are missing
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://disiaqzqfhmopynlsguw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpc2lhcXpxZmhtb3B5bmxzZ3V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwNjExNjYsImV4cCI6MjA3NzYzNzE2Nn0.7NeE-nvv8sINvzEd8egMV3cS7pGWhQbCrkE65BM68VU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Use an untyped client to avoid compile errors while the DB schema is being set up
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});